backend:
  image: node:5.10-onbuild
  ports:
   - "3001:3001"
  volumes:
   - .:/code
  working_dir: "/code"
  links:
   - mongodb
mongodb:
  image: mongo:3.2
  expose:
   - 27017
  ports:
   - "27017:27017"
